"""empty message

Revision ID: c03db014e82b
Revises: 
Create Date: 2024-08-06 18:38:19.506422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c03db014e82b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayments')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('email_address')
        batch_op.drop_index('nin_cust')
        batch_op.drop_index('rib_cust')

    op.drop_table('customers')
    op.drop_table('loans')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=24),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('account_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('balance',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_index('user_id_2')
        batch_op.drop_index('user_id_3')
        batch_op.create_unique_constraint(None, ['account_number'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'agencies', ['agency_id'], ['id'])

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_column('agency_name')
        batch_op.drop_column('agency_phone')
        batch_op.drop_column('agency_address')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id_transaction',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)
        batch_op.alter_column('amount',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_index('id_transaction')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.alter_column('email_address',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'agencies', ['agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('email_address',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('id_transaction', ['id_transaction'], unique=True)
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('id_transaction',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_address', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('agency_phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('agency_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('location')
        batch_op.drop_column('name')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('user_id_3', ['user_id'], unique=False)
        batch_op.create_index('user_id_2', ['user_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=15, scale=2),
               existing_nullable=False)
        batch_op.alter_column('account_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('account_number',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=24),
               existing_nullable=False)

    op.create_table('loans',
    sa.Column('loan_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('loan_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('outstanding_balance', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('loan_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email_address', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nin_cust', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('rib_cust', mysql.VARCHAR(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('rib_cust', ['rib_cust'], unique=True)
        batch_op.create_index('nin_cust', ['nin_cust'], unique=True)
        batch_op.create_index('email_address', ['email_address'], unique=True)

    op.create_table('repayments',
    sa.Column('repayment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('loan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('repayment_date', sa.DATE(), nullable=True),
    sa.Column('repayment_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], name='repayments_ibfk_1'),
    sa.PrimaryKeyConstraint('repayment_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
